{
 "title": "Webapp API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PUT /v1/user/self",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/user/self\",method=\"PUT\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/user/self\",method=\"PUT\"}"
    }
   ]
  },
  {
   "title": "DELETE /v1/alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/alert\",method=\"DELETE\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/alert\",method=\"DELETE\"}"
    }
   ]
  },
  {
   "title": "POST /v1/user/self",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/user/self\",method=\"POST\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/user/self\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "POST /v1/alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/alert\",method=\"POST\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/alert\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "POST /v1/user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/user\",method=\"POST\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/user\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "GET /v1/users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/users\",method=\"GET\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/users\",method=\"GET\"}"
    }
   ]
  },
  {
   "title": "GET /v1/helloworld",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome=\"SUCCESS\",uri=\"/v1/helloworld\",method=\"GET\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"webapp\",job=\"webapp\",outcome!=\"SUCCESS\",uri=\"/v1/helloworld\",method=\"GET\"}"
    }
   ]
  }
 ]
}
{
 "title": "Hacker News Cronjob",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "newstories_kafka_duration_count"
    },
    {
     "expr": "topstories_kafka_duration_count"
    },
    {
     "expr": "beststories_kafka_duration_count"
    }
   ]
  },
  {
   "title": "Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "newstories_kafka_duration_sum" },
    { "expr": "topstories_kafka_duration_sum" },
    { "expr": "beststories_kafka_duration_sum" }
   ]
  }
 ]
}
{
 "title": "Notifier Webapp",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Email Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sesService_send_seconds_count" }
   ]
  },
  {
   "title": "ElasticsearchDao",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_search_seconds_count"
    }
   ]
  },
  {
   "title": "EmailRecordDao",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "emailRecord_save_seconds_count" },
    {
     "expr": "emailRecord_getByUserIdAndStoryId_seconds_count"
    },
    {
     "expr": "emailRecord_getById_seconds_count"
    }
   ]
  },
  {
   "title": "GET /v1/helloworld",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"notifier-webapp\",job=\"notifier-webapp\",method=\"GET\",outcome=\"SUCCESS\",uri=\"/v1/helloworld\"}"
    },
    {
     "expr": "http_server_requests_seconds_count{app=\"notifier-webapp\",job=\"notifier-webapp\",method=\"GET\",outcome!=\"SUCCESS\",uri=\"/v1/helloworld\"}"
    }
   ]
  }
 ]
}
{
 "title": "Processor Webapp",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consume_kafka_duration_histogram_sum"
    },
    {
     "expr": "consume_kafka_duration_histogram_count"
    },
    {
     "expr": "create_story_duration_histogram_sum"
    },
    {
     "expr": "create_story_duration_histogram_count"
    },
    {
     "expr": "elastic_search_duration_histogram_sum"
    },
    {
     "expr": "elastic_search_duration_histogram_count"
    },
    {
     "expr": "get_story_duration_histogram_sum"
    },
    {
     "expr": "get_story_duration_histogram_count"
    },
    {
     "expr": "query_story_duration_histogram_sum"
    },
    {
     "expr": "query_story_duration_histogram_count"
    }
   ]
  },
  {
   "title": "Hackernews Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hackernews_count" },
    { "expr": "sum(hackernews_count)" }
   ]
  },
  {
   "title": "GET /hello",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hello_counter" },
    { "expr": "sum(hello_counter)" }
   ]
  },
  {
   "title": "Story Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "story_counter" },
    { "expr": "sum(story_counter)" }
   ]
  }
 ]
}