apiVersion: v2
name: metrics
description: Metrics Monitoring Stack for Kafka and Elasticsearch Clusters

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

sources:
- https://github.com/prometheus-community/helm-charts

dependencies:
- name: kube-prometheus-stack
  version: "14.3.0"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kubePrometheusStack.enabled
- name: prometheus-pushgateway
  version: "1.7.1"
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheusPushgateway.enabled
- name: prometheus-kafka-exporter
  version: "1.0.0"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kafkaExporter.enabled
- name: prometheus-elasticsearch-exporter
  version: "4.3.0"
  repository: https://prometheus-community.github.io/helm-charts
  condition: elasticsearchExporter.enabled
