## Configuration for kube-prometheus-stack subchart
##
kube-prometheus-stack:
  namespaceOverride: monitoring
  grafana:
    namespaceOverride: monitoring
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDelete: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
        - name: 'application'
          orgId: 1
          folder: ''
          type: file
          disableDelete: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/application
    dashboards:
      default:
        kubernetes:
          gnetId: 6417
          revision: 1
          datasource: Prometheus
        kafka:
          gnetId: 7589
          revision: 1
          datasource: Prometheus
        elasticsearch:
          gnetId: 9746
          revision: 1
          datasource: Prometheus
    dashboardsConfigMaps:
      application: grafana-dashboard-configmap
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
      - job_name: webapp
        tls_config:
          insecure_skip_verify: true
        metrics_path: '/actuator/prometheus'
        scrape_interval: 15s
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        # "prometheus.io/scrape = true" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        # "prometheus.io/path = <metric path>" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: keep
          regex: /actuator/prometheus
        # "prometheus.io/port = <port>" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: keep
          regex: 8080
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: default
      - job_name: processor-webapp
        tls_config:
          insecure_skip_verify: true
        metrics_path: '/metrics'
        scrape_interval: 15s
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        # "prometheus.io/scrape = true" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        # "prometheus.io/path = <metric path>" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: keep
          regex: /metrics
        # "prometheus.io/port = <port>" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: keep
          regex: 8080
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: default
      - job_name: notifier-webapp
        tls_config:
          insecure_skip_verify: true
        metrics_path: '/actuator/prometheus'
        scrape_interval: 15s
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        # "prometheus.io/scrape = true" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        # "prometheus.io/path = <metric path>" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: keep
          regex: /actuator/prometheus
        # "prometheus.io/port = <port>" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: keep
          regex: 8080
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: default
  kube-state-metrics:
    namespaceOverride: monitoring
  prometheus-node-exporter:
    namespaceOverride: monitoring

## Configuration for prometheus-pushgateway subchart
##
prometheus-pushgateway:
  serviceMonitor:
    enabled: truekube
    additionalLabels:
      release: prometheus

## Configuration for prometheus-kafka-exporter subchart
##
prometheus-kafka-exporter:
  kafkaServer:
    - kafka:9092
  prometheus:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus

## Configuration for prometheus-elasticsearch-exporter subchart
##
prometheus-elasticsearch-exporter:
  es:
    uri: http://elasticsearch-master:9200
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: prometheus